server:
  port: 25571

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/events_center
    username: root
    password: me#u6236kuGfsv
  data:
    redis:
      host: localhost
      port: 6379
      password: me#u6236kuGfsv
      database-index-authentication: 0
      database-index-file: 1
  mail:
    protocol: smtp
    host: smtp.163.com
    username: projecthelper@163.com
    password: XJMWVPFMWJCNKZKZ
    port: 25
    default-encoding: utf-8
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          ssl:
            trust: smtp.163.com
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  rabbitmq:
    host: localhost
    port: 25569
    username: user
    password: 56481367
    virtual-host: test

file-server:
  host: localhost
  port: 25572
  admin-token: ca20856d238e4b8e83ac91132456b796

user-token:
  file-server: 51cc09f300354fdba303d98322ef1698

amap-security-js-code:
  358452be7b918daed666bc8444a4608d

logging:
  file:
    name: ./logs/EventsCenter.log
    path: ./logs
  level:
    root: INFO
