server:
  port: 25571

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.113.54:3306/events_center
    username: root
    password: me#u6236kuGfsv
  data:
    redis:
      host: 47.107.113.54
      port: 6379
      password: me#u6236kuGfsv
      database-index-authentication: 0
      database-index-file: 1
  mail:
    protocol: smtp
    host: smtp.163.com
    username: eventcentersustech@163.com
    password: ZZSKLQLTJQTWSWBZ
    port: 25
    default-encoding: utf-8
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          ssl:
            trust: smtp.163.com
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  rabbitmq:
    host: 47.107.113.54
    port: 25569
    username: user
    password: 56481367
    virtual-host: test

file-server:
  host: 47.107.113.54
  port: 25576
  admin-token: ca20856d238e4b8e83ac91132456b796

user-token:
  file-server: 51cc09f300354fdba303d98322ef1698

amap-security-js-code:
  358452be7b918daed666bc8444a4608d

logging:
  file:
    name: .data/logs/EventsCenter.log
    path: .data/logs
  level:
    root: INFO

alipay:
  appId: 9021000136692684
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCT7bir9E/wN48ZmL4FW9CNcaU4Bc2Xtd3vd/CJ5v6w6t+NULe2NwGoOpvO9LzYZy1QBr+yK83t/rRqGcyTuthR+7P7B8iIjiW6e6qxAlYJ1q9rfMNZD04ITVnVAdvke8bxe2p2j8Uuki38V2ySAGHGcL1AHUrm+mmYN6BcZGFDfvL8vIKzqwkH7fKIeU/9Vkirak8J9EbscQsx0EW63JMli8bIggI94ieanor9N+0en/WJv1RPH3OmnRkJjOpBB1Shnx38EaaJ2qkDA4HX27ZNxSCgUXHjHLerR0iJ9+72o8GuBoQh7FpDUpXXz+I32U5FZjOPjmp0HNK8vp8j3QqDAgMBAAECggEATnR3ywsKEncE+ChgL2tgkoPBgpLhVSLpkAXmltziG2aWJda3eHZ39IcQ95QpTAR8rcLGjHJbB2xctyDztS4VaHW8INkh6/qn292Wy8ZXZ2RrKPDEkklhs1mC2UvhGa7j9lLkRfk+NNLmfLzJIi39rUdBt+1ROmt48XgfHqFGTIsLIxe63AV08T2/eW7oa4Hi3vgow6MJ1pxAjS1vBsoJJKCYgP3RZKXb8RXtnjjcbgr4Pbp02n9LpeaXQ5rwZja1vWi2HMGb89QqKsh69AGDzRt6Q3MyCd7RXHy/qKV4TbPfXTfOnCGZu8uzNv2ayEjudww+IKjNEeF8pOEaZwr10QKBgQDL6E92FV9seG/8p3ITxlLuzIp+F2otzihNImTfGFyoF1wX8yTR2DbBNU8kpQLlJwkVpsRvgJgRqiosZAKoXzXAwfViXlE/srqSEPGKrhq5ndd+2a7y+T/RMf2U4PsejJ1y7sPCnMQ5zVA38FY9C/Is5jmgW0pHRxa9LlrTlfw6FwKBgQC5uFq9Xtleu1bj3qdirEeb6l8D7lAyWqYUntH/Lm5NFNxu2Ph5bVl+l0MQs2ZQdrAXSFmEiVMAFDUT18TxfV0eh7+gNPJY7Jn4G5ruTnktfAnNF1yHr1yxPj9f7A/D4nlYJt2tUz+fcRBh+ryNbUdQgl/m4YxJ/EqbM9+M+nIydQKBgGJdZA/Dya+q/eL05+wwLQuzsk+XfgowvHJRWDXjK7eO5UdMbQOp+OgFjnNQAvCGfzRpqbNcZn+HBic566pLm8OsDXLxquI+lxAlik/rI0tNoIo5+tKNeMKzCfBLA/k9viqWkesM8wArUjpZ/1AdtisAuOXphBCUc5y5guk1HmLrAoGADw8VvHkuYvIJz5xEMkoJ3Gian7T5J7wV72IZYPmg0/s3DH3nV+E3+n3FYFtLloapLJofOBHyevUogJ1kSLiDjnAvZ4wjgnZc3bNPUrdmN/vwx4J3bEEZ4P1NIjf/50A72pv8KYuwgvsl+uvb0hPkTnDj2dK8D1u3qPIB1GqSS+kCgYAEZdiIy5GGlu7JONQml/l6gRcNR2uNcUB762jNIc2KqxzSnolTAUA+o2iiYCTjX+uQiV9WKRVQnvxq2V7ME7drRrtBbC/lgfNarK3Qo2iZr17F4DgxsdmpY979dWcYxF8Fn9vaPO01CB3LGzW8il3BBADU3GhSfYFhBMEHY6DMLA==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtVLxz/P63j250D6sT7ocEBVUs3og8gMrDkylyYVrE4ReJ7sk1RYwIiXUn/2l1irnUEAZGeMS+hklBEssNAQsUAXazDr1xcvmZ8V9Gu7y2JpnMMcCQpKfrIcKf++6XRskz3Mj239mUvitWd/VD18+P9hoLlI9ipjFTFfk1zUcRz2/TkfqpngOxioc3ik1WkgVbdlYZkCR/368JsRbx4WnLPw/tNmQyS5P329+h58gybfIgHJew28hGtxvSlFyqcgafWk1JCm19N8FcYPMDjTDslA0ZOJz4xxXXyAGlD+ATY04pfO47/owr4wTAIrWxkEIoHohvzkHCmsNQKgBEP5UPwIDAQAB
  notifyUrl: http://localhost:8083/alipay/notify