# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy backend to Aliyun

on:
  push:
    branches: [ "deploy", "actions" ]
  pull_request:
    branches: [ "deploy", "actions" ]

jobs:
  build-file-server-docker-image-and-upload-to-tyc-server:
    runs-on: ubuntu-latest
    environment: deploy-to-aliyun
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: "{{defaultContext}}:fileServer"
          push: true
          tags: qy02/events_center_file_server
      - name: Export Docker image to tar
        run: |
          docker save -o events_center_file_server.tar qy02/events_center_file_server
          chmod 777 events_center_file_server.tar
      - name: Upload Docker image tar to tyc server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.TYC_SERVER_USERNAME }}
          password: ${{ secrets.TYC_SERVER_PASSWORD }}
          port: ${{ secrets.TYC_SERVER_PORT }}
          source: 'events_center_file_server.tar'
          target: '/home/shadowfall/Documents/Software_Engineering/auto-deployment/docker-image-tars'

  build-backend-docker-image-and-upload-to-aliyun-server:
    runs-on: ubuntu-latest
    environment: deploy-to-aliyun
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: qy02/events_center_backend
      - name: Export Docker image to tar
        run: |
          docker save -o events_center_backend.tar qy02/events_center_backend
          chmod 777 events_center_backend.tar
      - name: Upload Docker image tar to aliyun server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: 'events_center_backend.tar'
          target: '/root/SE/auto-deployment/docker-image-tars'

  build-frontend-docker-image-and-upload-to-aliyun-server:
    runs-on: ubuntu-latest
    environment: deploy-to-aliyun
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: qy02/events_center_frontend
      - name: Export Docker image to tar
        run: |
          docker save -o events_center_frontend.tar qy02/events_center_frontend
          chmod 777 events_center_frontend.tar
      - name: Upload Docker image tar to aliyun server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: 'events_center_frontend.tar'
          target: '/root/SE/auto-deployment/docker-image-tars'

  build-llm-service-docker-image-and-upload-to-tyc-server:
    runs-on: ubuntu-latest
    environment: deploy-to-aliyun
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          ref: deploy
      - name: Add env
        working-directory: ./LLM_handler/clash-for-linux-master
        run: echo "${{ secrets.LLM_SERVICE_ENV }}" > .env
      - name: Build Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: "./LLM_handler"
          push: false
          tags: events_center_llm_service
      - name: Export Docker image to tar
        run: |
          docker save -o ./LLM_handler/events_center_llm_service.tar events_center_llm_service
          chmod 777 ./LLM_handler/events_center_llm_service.tar
      - name: Upload Docker image tar to tyc server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.TYC_SERVER_USERNAME }}
          password: ${{ secrets.TYC_SERVER_PASSWORD }}
          port: ${{ secrets.TYC_SERVER_PORT }}
          source: './LLM_handler/events_center_llm_service.tar'
          target: '/home/shadowfall/Documents/Software_Engineering/auto-deployment/docker-image-tars'

  build-recommend-service-docker-image-and-run-on-tyc-server:
    runs-on: ubuntu-latest
    environment: deploy-to-aliyun
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: "{{defaultContext}}:REC"
          push: true
          tags: qy02/events_center_recommend_service
      - name: update-and-start-events-center-recommend-service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.TYC_SERVER_USERNAME }}
          password: ${{ secrets.TYC_SERVER_PASSWORD }}
          port: ${{ secrets.TYC_SERVER_PORT }}
          script: |
            docker stop events_center_recommend_service || true
            docker rm events_center_recommend_service || true
            docker rmi qy02/events_center_recommend_service || true
            docker pull qy02/events_center_recommend_service
            docker run -d --name events_center_recommend_service -e TZ=Asia/Shanghai qy02/events_center_recommend_service

  update-and-start-events-center-containers:
    needs: [build-file-server-docker-image-and-upload-to-tyc-server, build-backend-docker-image-and-upload-to-aliyun-server, build-frontend-docker-image-and-upload-to-aliyun-server, build-llm-service-docker-image-and-upload-to-tyc-server]
    runs-on: ubuntu-latest
    environment: deploy-to-aliyun
    steps:
      - name: update-and-start-events-center-file-server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.TYC_SERVER_USERNAME }}
          password: ${{ secrets.TYC_SERVER_PASSWORD }}
          port: ${{ secrets.TYC_SERVER_PORT }}
          script: |
            docker stop events_center_file_server || true
            docker rm events_center_file_server || true
            docker rmi qy02/events_center_file_server || true
            docker load -i /home/shadowfall/Documents/Software_Engineering/auto-deployment/docker-image-tars/events_center_file_server.tar
            docker run -d --name events_center_file_server -p 25572:25572 -e TZ=Asia/Shanghai -v /home/shadowfall/Documents/Software_Engineering/auto-deployment/fileServerData:/app/data qy02/events_center_file_server    steps:
      - name: update-and-start-events-center-backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop events_center_backend || true
            docker rm events_center_backend || true
            docker rmi qy02/events_center_backend || true
            docker load -i /root/SE/auto-deployment/docker-image-tars/events_center_backend.tar
            docker run -d --name events_center_backend -p 25571:25571 -e TZ=Asia/Shanghai -v /root/SE/auto-deployment/backendData:/app/data qy02/events_center_backend
      - name: update-and-start-events-center-frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop events_center_frontend || true
            docker rm events_center_frontend || true
            docker rmi qy02/events_center_frontend || true
            docker load -i /root/SE/auto-deployment/docker-image-tars/events_center_frontend.tar
            docker run -d --name events_center_frontend -p 25577:80 -e TZ=Asia/Shanghai qy02/events_center_frontend
      - name: update-and-start-events-center-llm-service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.TYC_SERVER_USERNAME }}
          password: ${{ secrets.TYC_SERVER_PASSWORD }}
          port: ${{ secrets.TYC_SERVER_PORT }}
          script: |
            docker stop events_center_llm_service || true
            docker rm events_center_llm_service || true
            docker rmi events_center_llm_service || true
            docker load -i /home/shadowfall/Documents/Software_Engineering/auto-deployment/docker-image-tars/events_center_llm_service.tar
            docker run -d --name events_center_llm_service -e TZ=Asia/Shanghai --env-file /home/shadowfall/.llmrc events_center_llm_service
